export WEZTERM_TOOLS_ROOT_WIN="${WEZTERM_TOOLS_ROOT:-C:/Users/qwer/Desktop/WezTerm/Tools}"

if command -v cygpath >/dev/null 2>&1; then
  export WEZTERM_TOOLS_ROOT="$(cygpath -u "$WEZTERM_TOOLS_ROOT_WIN")"
else
  export WEZTERM_TOOLS_ROOT="${WEZTERM_TOOLS_ROOT_WIN//\\//}"
fi

if [[ -z ${USER-} ]] && [[ -n ${USERNAME-} ]]; then
  export USER="$USERNAME"
fi

prepend_path() {
  local candidate="$1"

  if [ -d "$candidate" ]; then
    PATH="$candidate:$PATH"
  fi
}

prepend_path "$WEZTERM_TOOLS_ROOT"
prepend_path "$WEZTERM_TOOLS_ROOT/nvim/bin"
prepend_path "$WEZTERM_TOOLS_ROOT/ripgrep"
prepend_path "$WEZTERM_TOOLS_ROOT/fd"
prepend_path "$WEZTERM_TOOLS_ROOT/lazygit"
prepend_path "$WEZTERM_TOOLS_ROOT/yazi"
prepend_path "$WEZTERM_TOOLS_ROOT/bat"
prepend_path "$WEZTERM_TOOLS_ROOT/eza"
prepend_path "$WEZTERM_TOOLS_ROOT/starship"

export PATH
export EDITOR="nvim"
export VISUAL="nvim"
export GIT_EDITOR="nvim"
export STARSHIP_CONFIG="${STARSHIP_CONFIG:-$HOME/.wezterm-config/wezterm/starship.toml}"

if [[ $- == *i* ]] && [[ -r "$WEZTERM_TOOLS_ROOT/ble.sh/ble.sh" ]]; then
  source -- "$WEZTERM_TOOLS_ROOT/ble.sh/ble.sh" --attach=none
fi

alias vim='nvim'
alias lg='lazygit'
alias y='yazi'
alias ..='cd ..'
alias gs='git status -sb'

if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -la --group-directories-first'
fi

if command -v bat >/dev/null 2>&1; then
  alias cat='bat --paging=never'
fi

if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
  if declare -F starship_precmd >/dev/null 2>&1; then
    starship_precmd
  fi
fi

if [[ $- == *i* ]] && [[ -n ${BLE_VERSION-} ]]; then
  bleopt complete_auto_delay=120
  bleopt prompt_eol_mark=''
  bleopt exec_errexit_mark=
  bleopt exec_elapsed_mark=
  ble-attach
fi